// Generated by CoffeeScript 1.7.1
(function() {
  var arr, data, fib, fibo, hello, html, i, name, pos, size, square, val, value, _i, _j, _len, _len1;

  hello = function() {
    return console.log("Hello World");
  };

  square = function(x) {
    return x * x;
  };

  fib = function(n) {
    if (n < 2) {
      return n;
    } else {
      return fib(n - 1) + fib(n - 2);
    }
  };

  fibo = function(n) {
    if (n < 2) {
      return n;
    } else {
      return fibo(n - 1) + fibo(n(-2));
    }
  };

  name = "Nao";

  console.log("My name is " + name + "!");

  pos = {
    x: 100,
    y: 200,
    dump: function() {
      return console.log("x:" + this.x + ",y:" + this.y);
    }
  };

  size = {
    width: 100,
    height: 100
  };

  myFunc({
    width: 100,
    height: 100
  });

  arr = ["a", "b", "c", "d", "e"];

  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    val = arr[_i];
    console.log(val);
  }

  for (i = _j = 0, _len1 = arr.length; _j < _len1; i = ++_j) {
    val = arr[i];
    console.log("" + i + ": " + val);
  }

  data = {
    x: 100,
    y: 200
  };

  for (name in data) {
    value = data[name];
    console.log("" + name + ": " + value);
  }

  if (typeof myName !== "undefined" && myName !== null) {
    console.log("yes");
  } else {
    console.log("no");
  }

  if (typeof console !== "undefined" && console !== null) {
    if (typeof console.log === "function") {
      console.log("Hello World");
    }
  }

  html = '<html>\n<head>\n  <title>CoffeeScript</title>\n</head>\n<body>\n  <table>\n    <tr>\n      <td></dt>\n    </tr>\n  </table>\n</body>\n</html>';

  hello();

}).call(this);
